### ISSUE TITLE
Google translate link on mobile menu duplicates after multiple hamburger click

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1638]
Hi.
We are expecting issue, when at mobile mode user clicks on hamburger menu many time, translation widget is adding many times.

We need to add once check at this place:
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_gtranslate/js/openy_gtranslate.js#L36

![image](https://user-images.githubusercontent.com/3023950/60502664-eb7ff500-9cc6-11e9-8962-04dffb45b035.png)

**Comment by paige-kiecker** [comment]
@anpolimus this has been resolved.

**Comment by akaleMulder** [comment]
I still see the issue with the SELECT LANGUAGE menu item duplicates every time a menu on mobile is opened. Seems like the issue is specific to the Carnation theme.

Steps to reproduce:

1. Open http://sandbox.openy.org/ from a mobile phone (can be reproduced using the developer console of a browser as well). I used Google Chrome Version 79.0.3945.88 on macOS Catalina version 10.15.2 and Google Chrome Version 79.0.3945.88 on Android 9 (OnePlus 5T).
2. Click on the hamburger menu icon at the top right corner to open the menu.
3. Click on the cross icon at the top right corner to close the menu.
4. Once the cross icon is clicked, the additional SELECT LANGUAGE menu item will appear.
5. Once the hamburger menu icon is clicked, another SELECT LANGUAGE menu item will appear.
6. An additional SELECT LANGUAGE menu item appears every time steps 2 and 3 are repeated.

Another thing I've noticed is that choosing a language does not translate the content. Nothing happens.

UPD: the issue can be reproduced in Lily and Rose themes as well.

**Comment by dwells-tn** [comment]
@akaleMulder @anpolimus  I ran into this at iPhone X/XS resolution on Firefox inspector and on Chrome on my Pixel 3 independent of this issue. Adding screenshots

![Carnation](https://user-images.githubusercontent.com/52217125/73102243-0d390780-3eb7-11ea-92e1-30e3286e89cc.png)

![Lily](https://user-images.githubusercontent.com/52217125/73102260-1924c980-3eb7-11ea-98e5-13e126957aaf.png)

![Rose](https://user-images.githubusercontent.com/52217125/73102274-1f1aaa80-3eb7-11ea-9d22-255b5770ea83.png)

**Comment by dwells-tn** [comment]
I was sometimes seeing this after just one tap of the nav.
