### ISSUE TITLE
Location Amenities Filter Logic is Broken

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1770]
Currently when 2 or more amenities boxes on a Locations page are checked, all locations that have AT LEAST ONE of the amenities selected display. Instead, the results should show you only locations that have all the amenities selected.

The logic should be changed to AND instead of the current OR function.

**Comment by anpolimus** [comment]
Hi, @paige-kiecker.
This issue is fixed at PR: https://github.com/ymcatwincities/openy/pull/1778/files
Please check this issue on new build and close this issue if your test would be successful.

**Comment by paige-kiecker** [comment]
@podarok can you look into this Monday?

**Comment by paige-kiecker** [comment]
@anpolimus the amenities issue still persists so I do not believe your PR resolved it. I will escalate to IXM officially

**Comment by anpolimus** [comment]
@paige-kiecker - we will look to it and adding this issue to our Feb release scope.
